apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-3
  description: Description of my new service
  tags:
    - python
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: AppOwnerTeamA
